name: ABT

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  python-check:
    name: Python Syntax Check
    if: ${{ hashFiles('**/*.py') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@07d4e924bc89c2c3df8afc2a3e74c377b68d9d06
        with:
          python-version: '3.x'
      - name: Check Python syntax
        run: |
          echo "🔍 Checking Python files..."
          python -m py_compile $(find . -name "*.py" || echo "")

  nodejs-check:
    name: NodeJS Syntax Check
    if: ${{ hashFiles('**/*.js') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@536e94c570c9b1ae3c24a8707c7ff7962180b86d
        with:
          node-version: '20'
      - name: Check JavaScript syntax
        run: |
          echo "🔍 Checking JavaScript files..."
          for file in $(find . -name "*.js" || echo ""); do
            node --check "$file"
          done

  cpp-check:
    name: C++ Syntax Check
    if: ${{ hashFiles('**/*.cpp') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check C++ syntax
        run: |
          echo "🔍 Checking C++ files..."
          for file in $(find . -name "*.cpp" || echo ""); do
            g++ -fsyntax-only "$file"
          done

  java-check:
    name: Java Syntax Check
    if: ${{ hashFiles('**/*.java') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@7d2fa46a334d9a9f98c0122396fa6d120b228310
        with:
          java-version: '21'
      - name: Check Java syntax
        run: |
          echo "🔍 Checking Java files..."
          for file in $(find . -name "*.java" || echo ""); do
            javac -Xlint "$file"
          done

  php-check:
    name: PHP Syntax Check
    if: ${{ hashFiles('**/*.php') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@e6e6fdb21d10f8c245fa7bd2dbd50894c8fdc7e5
        with:
          php-version: '8.3'
      - name: Check PHP syntax
        run: |
          echo "🔍 Checking PHP files..."
          for file in $(find . -name "*.php" || echo ""); do
            php -l "$file"
          done
