name: ABT

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  python-check:
    name: Python Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: List Python files found
        run: |
          echo "🐍 Python files found:"
          find . -name "*.py" || echo "No Python files found"
      - name: Check Python syntax
        run: |
          files=$(find . -name "*.py")
          if [ -z "$files" ]; then
            echo "No Python files to check."
          else
            python -m py_compile $files
          fi

  nodejs-check:
    name: NodeJS Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: List JS files found
        run: |
          echo "🟨 JS files found:"
          find . -name "*.js" || echo "No JS files found"
      - name: Check JavaScript syntax
        run: |
          files=$(find . -name "*.js")
          if [ -z "$files" ]; then
            echo "No JS files to check."
          else
            for file in $files; do
              node --check "$file"
            done
          fi

  cpp-check:
    name: C++ Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List C++ files found
        run: |
          echo "🔵 C++ files found:"
          find . -name "*.cpp" || echo "No C++ files found"
      - name: Check C++ syntax
        run: |
          files=$(find . -name "*.cpp")
          if [ -z "$files" ]; then
            echo "No C++ files to check."
          else
            for file in $files; do
              g++ -fsyntax-only "$file"
            done
          fi

  java-check:
    name: Java Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: List Java files found
        run: |
          echo "☕ Java files found:"
          find . -name "*.java" || echo "No Java files found"
      - name: Check Java syntax
        run: |
          files=$(find . -name "*.java")
          if [ -z "$files" ]; then
            echo "No Java files to check."
          else
            for file in $files; do
              javac -Xlint "$file"
            done
          fi

  php-check:
    name: PHP Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: List PHP files found
        run: |
          echo "🐘 PHP files found:"
          find . -name "*.php" || echo "No PHP files found"
      - name: Check PHP syntax
        run: |
          files=$(find . -name "*.php")
          if [ -z "$files" ]; then
            echo "No PHP files to check."
          else
            for file in $files; do
              php -l "$file"
            done
          fi
